### ISSUE TITLE
Problem in Vaadin 14 (npm mode) with @HtmlImport annotation inhertied by clients

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-board-flow#105]
2019-10-28 17:48:10,337 ERROR [com.vaadin.flow.component.internal.ComponentMetaData] (default task-2)
de.mach.selfservices.ui.components.layout.MachRow has only @HtmlImport annotation(s) which is ignored in Vaadin 14+. This annotation is only useful in compatibility mode. In order to use a Polymer template inside a component in Vaadin 14+, @JsModule annotation should be used. And to use a css file, {@link CssImport} should be used. If you want to be able to use your component in both compatibility mode and normal mode of Vaadin 14+ you need to have @HtmlImport along with @JsModule and/or @CssImport annotations.Go to Vaadin 14 Migration Guide (https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#3-convert-polymer-2-to-polymer-3) to see how to migrate templates from Polymer 2 to Polymer 3.
2019-10-28 17:48:10,337 ERROR [com.vaadin.flow.component.internal.ComponentMetaData] (default task-2)
com.vaadin.flow.component.board.Row has only @HtmlImport annotation(s) which is ignored in Vaadin 14+. This annotation is only useful in compatibility mode. In order to use a Polymer template inside a component in Vaadin 14+, @JsModule annotation should be used. And to use a css file, {@link CssImport} should be used. If you want to be able to use your component in both compatibility mode and normal mode of Vaadin 14+ you need to have @HtmlImport along with @JsModule and/or @CssImport annotations.Go to Vaadin 14 Migration Guide (https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#3-convert-polymer-2-to-polymer-3) to see how to migrate templates from Polymer 2 to Polymer 3.
2019-10-28 17:48:10,339 ERROR [com.vaadin.flow.component.internal.ComponentMetaData] (default task-2)
de.mach.selfservices.catalog.ui.TilePreviewPage has only @HtmlImport annotation(s) which is ignored in Vaadin 14+. This annotation is only useful in compatibility mode. In order to use a Polymer template inside a component in Vaadin 14+, @JsModule annotation should be used. And to use a css file, {@link CssImport} should be used. If you want to be able to use your component in both compatibility mode and normal mode of Vaadin 14+ you need to have @HtmlImport along with @JsModule and/or @CssImport annotations.Go to Vaadin 14 Migration Guide (https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#3-convert-polymer-2-to-polymer-3) to see how to migrate templates from Polymer 2 to Polymer 3.

Please can you fix asap?

**Comment by alvarezguille** [comment]
The issue was in project setup, `vaadin-board-flow` version was pinned and overriding `3.0.0` which is compatible with both bower and npm mode.
It was fixed after removing the pinned version number and letting `vaadin-bom` override it.
