### ISSUE TITLE
Not in BOM of commercial components?

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-board-flow#106]
```
<groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>

```
So when when I use this "commercial" variant with version 14.0.11 I have to add a version number and a dependency on vaadin-board-flow.

**Comment by alvarezguille** [comment]
`vaadin-board-flow` version is defined in `vaadin-spring-bom` that is imported and used by `vaadin-bom`, version commercial components is defined in bom.
